Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_) :

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

The difference between the data type of variables list_ and array_list is that the data type of list_ is a list while the data type of array_list is a numpy array. Here’s the code to print the data types of both variables:

In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_) : 

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

for i in list_:
    print(type(i))

for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3.Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_ , dtype = int) :

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list?
If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes, there is a difference in the data type of the elements present in both the variables, list_ and array_list. The data type of the elements present in list_ is string whereas the data type of the elements present in array_list is integer.

Here are the data types of each and every element present in both the variables:

In [3]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_ , dtype = int)

print("Data types of each and every element present in list_ : ")
for i in list_:
    print(type(i), end=", ")
    
print("\nData types of each and every element present in array_list : ")
for i in array_list:
    print(type(i), end=", ")

Data types of each and every element present in list_ : 
<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, 
Data types of each and every element present in array_list : 
<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, 

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list) :

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
import numpy as np

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
